CREATE DATABASE IF NOT EXISTS DEVBOOK;

USE DEVBOOK;

DROP TABLE IF EXISTS USERS;

CREATE TABLE USERS (
    id INT PRIMARY KEY AUTO_INCREMENT PRIMARY KEY,
    name VARCHAR(50) NOT NULL,
    nick VARCHAR(50) NOT NULL unique,
    email VARCHAR(50) NOT NULL unique,
    password VARCHAR(50) NOT NULL,
    CREATED_AT DATETIME default CURRENT_TIMESTAMP()
)ENGINE=InnoDB DEFAULT CHARSET=utf8;